import Head from "next/head";
import React, { FC, PropsWithChildren } from "react";
import { Nabvar } from "../Nabvar";
import Link from "next/link";
import Image from "next/image";
import styles from "./MainLayout.module.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const MainLayaout:FC<PropsWithChildren>= ({ children }) => {
  return (
    <>
      <Head>
        <title>WELI NEXT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nabvar></Nabvar>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}></div>
        {children}
      </main>
    </>
  );
};
